### ISSUE TITLE
Synchronisation du calendrier

### ISSUE THREAD

**Issue by PM2000-maker** [philippe-nougaillon/crystal-data7#43]
J'ai créé des entrées avec dates et j'ai synchronisé mon calendrier sur nextcloud.
Sauf qu'ils s'affichent à des dates aléatoires sur nextcloud qui ne correspondent pas à celles de mes entrées dans crystal-data
![image](https://github.com/philippe-nougaillon/crystal-data7/assets/52786909/39ec76f5-ecb8-46ca-9fff-4efc7fd47481)
![image](https://github.com/philippe-nougaillon/crystal-data7/assets/52786909/3d543d75-5960-4273-8a8a-b2b4464e91c4)

**Comment by P-edacquet** [comment]
Bonjour,

Nous avons fait des corrections et des tests avec Google Calendar. Tout semble OK.
Pouvez-vous confirmer que cela marche aussi de votre côté, avec nextcloud ?

**Comment by PM2000-maker** [comment]
Oui en effet ça s'est mi à jour directement.
Merci !
