### ISSUE TITLE
Affichage titre objet

### ISSUE THREAD

**Issue by PM2000-maker** [philippe-nougaillon/crystal-data7#49]
Tout les titres de mes objets s'affichent bien sauf dans un objet ou mes titres apparaissent en blanc sur blanc.
![image](https://github.com/philippe-nougaillon/crystal-data7/assets/52786909/ca319eed-f983-4571-931a-58a0d74e887a)

**Comment by philippe-nougaillon** [comment]
Bizarre bizarre...
Pourriez-vous nous montrer aussi la structure de l'objet ?

**Comment by philippe-nougaillon** [comment]
bonjour
on pense avoir trouvé d'où venait le problème
pouvez-vous nous dire si de votre côté les titres s'affichent maintenant correctement ?
